// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsi-qBjJHXmtZx6eIlwiUkBQtMtuhqSV8',
    appId: '1:843445647416:web:cce7c6c7d6f48979f2cecd',
    messagingSenderId: '843445647416',
    projectId: 'my-project-bbcb1',
    authDomain: 'my-project-bbcb1.firebaseapp.com',
    storageBucket: 'my-project-bbcb1.appspot.com',
    measurementId: 'G-CSTF1VH8W0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeP8UW1w_kSdHaSnI9aTCTg8vQJZOJJGE',
    appId: '1:843445647416:android:cfeb91b0a2b9bd5cf2cecd',
    messagingSenderId: '843445647416',
    projectId: 'my-project-bbcb1',
    storageBucket: 'my-project-bbcb1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrgRUlGH4bDU8jM4feI7R836Vxe2waOJQ',
    appId: '1:843445647416:ios:03e2f582d9cde161f2cecd',
    messagingSenderId: '843445647416',
    projectId: 'my-project-bbcb1',
    storageBucket: 'my-project-bbcb1.appspot.com',
    iosClientId: '843445647416-mq5mld6rjkjfphgitcpalm5pdlr2kqkl.apps.googleusercontent.com',
    iosBundleId: 'com.example.personalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrgRUlGH4bDU8jM4feI7R836Vxe2waOJQ',
    appId: '1:843445647416:ios:03e2f582d9cde161f2cecd',
    messagingSenderId: '843445647416',
    projectId: 'my-project-bbcb1',
    storageBucket: 'my-project-bbcb1.appspot.com',
    iosClientId: '843445647416-mq5mld6rjkjfphgitcpalm5pdlr2kqkl.apps.googleusercontent.com',
    iosBundleId: 'com.example.personalProject',
  );
}
